SUMMARY_STATS_BY_PARAM = 'summary_stats_param'
SUMMARY_STATS_BY_LOC = 'summary_stats_loc'
DATA_DIST = 'data_distribution'
FOR_STATISTICAL_ANALYSIS = 'stat_analysis'
FOR_SPATIAL_ANALYSIS = 'spatial_analysis'
AVG_MONTHLY_ANALYSIS = 'avg_monthly_analysis'
UPDATING_ANALYSIS = 'updateing_analysis'
MESSAGE_COUNTS_HOURLY = 'message_counts_hourly'